import sys

input = sys.stdin.readline
n = int(input())
s = input().split()
for c in s:
    match c:
        case ".-":
            print("A", end="")
        case "-...":
            print("B", end="")
        case "-.-.":
            print("C", end="")
        case "-..":
            print("D", end="")
        case ".":
            print("E", end="")
        case "..-.":
            print("F", end="")
        case "--.":
            print("G", end="")
        case "....":
            print("H", end="")
        case "..":
            print("I", end="")
        case ".---":
            print("J", end="")
        case "-.-":
            print("K", end="")
        case ".-..":
            print("L", end="")
        case "--":
            print("M", end="")
        case "-.":
            print("N", end="")
        case "---":
            print("O", end="")
        case ".--.":
            print("P", end="")
        case "--.-":
            print("Q", end="")
        case ".-.":
            print("R", end="")
        case "...":
            print("S", end="")
        case "-":
            print("T", end="")
        case "..-":
            print("U", end="")
        case "...-":
            print("V", end="")
        case ".--":
            print("W", end="")
        case "-..-":
            print("X", end="")
        case "-.--":
            print("Y", end="")
        case "--..":
            print("Z", end="")
        case ".----":
            print("1", end="")
        case "..---":
            print("2", end="")
        case "...--":
            print("3", end="")
        case "....-":
            print("4", end="")
        case ".....":
            print("5", end="")
        case "-....":
            print("6", end="")
        case "--...":
            print("7", end="")
        case "---..":
            print("8", end="")
        case "----.":
            print("9", end="")
        case "-----":
            print("0", end="")
        case "--..--":
            print(",", end="")
        case ".-.-.-":
            print(".", end="")
        case "..--..":
            print("?", end="")
        case "---...":
            print(":", end="")
        case "-....-":
            print("-", end="")
        case ".--.-.":
            print("@", end="")
